
export default new Map([
["src/content/blog/en/ai-assisted-development-without-building-a-mess.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fai-assisted-development-without-building-a-mess.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/ai-clarity-framework-mvp-roadmap.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fai-clarity-framework-mvp-roadmap.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/claude-code-workflows.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fclaude-code-workflows.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/how-much-does-an-mvp-cost.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Fhow-much-does-an-mvp-cost.mdx&astroContentModuleFlag=true")],
["src/content/blog/en/react-typescript-node-mvp-stack.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fen%2Freact-typescript-node-mvp-stack.mdx&astroContentModuleFlag=true")],
["src/content/blog/es/ai-assisted-development-without-building-a-mess.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fes%2Fai-assisted-development-without-building-a-mess.mdx&astroContentModuleFlag=true")],
["src/content/blog/es/ai-clarity-framework-mvp-roadmap.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fes%2Fai-clarity-framework-mvp-roadmap.mdx&astroContentModuleFlag=true")],
["src/content/blog/es/claude-code-workflows.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fes%2Fclaude-code-workflows.mdx&astroContentModuleFlag=true")],
["src/content/blog/es/how-much-does-an-mvp-cost.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fes%2Fhow-much-does-an-mvp-cost.mdx&astroContentModuleFlag=true")],
["src/content/blog/es/react-typescript-node-mvp-stack.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fes%2Freact-typescript-node-mvp-stack.mdx&astroContentModuleFlag=true")],
["src/content/blog/fr/ai-assisted-development-without-building-a-mess.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffr%2Fai-assisted-development-without-building-a-mess.mdx&astroContentModuleFlag=true")],
["src/content/blog/fr/ai-clarity-framework-mvp-roadmap.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffr%2Fai-clarity-framework-mvp-roadmap.mdx&astroContentModuleFlag=true")],
["src/content/blog/fr/claude-code-workflows.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffr%2Fclaude-code-workflows.mdx&astroContentModuleFlag=true")],
["src/content/blog/fr/how-much-does-an-mvp-cost.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffr%2Fhow-much-does-an-mvp-cost.mdx&astroContentModuleFlag=true")],
["src/content/blog/fr/react-typescript-node-mvp-stack.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ffr%2Freact-typescript-node-mvp-stack.mdx&astroContentModuleFlag=true")]]);
		