import type { ServiceContent } from './en';

export const servicesContentEs: Record<string, ServiceContent> = {
  'ai-web-development-newsletter': {
    title: "Newsletter de Desarrollo Web con IA",
    meta: {
      title: "Newsletter de Desarrollo Web con IA para Desarrolladores y Fundadores",
      description:
        "Una newsletter mensual de IA centrada en IA generativa, herramientas de código, agentes de IA y flujos de trabajo prácticos de desarrollo web para desarrolladores, fundadores y freelancers.",
    },
    badge: "Newsletter",
    hero: {
      h1: "Mantente a la vanguardia del desarrollo web con IA sin perder horas leyendo ruido",
      subtitle:
        "Una newsletter mensual práctica para desarrolladores, fundadores y freelancers que quieren entender lo que importa en IA generativa, herramientas de código y desarrollo web asistido por IA.",
      primaryCta: "Unirse a la lista de espera",
    },
    answer:
      "Un resumen mensual práctico sobre lo que realmente importa en IA generativa, herramientas de código y desarrollo web. Seleccionado para desarrolladores, fundadores y freelancers que quieren tomar buenas decisiones sin leerlo todo.",
    useCases: [],
    heroCard: {
      type: "checklist",
      title: "CADA NÚMERO INCLUYE",
      items: [
        "Herramientas de IA que vale la pena probar este mes",
        "Ideas de flujo de trabajo de código",
        "Prompts prácticos",
        "Qué ignorar",
        "Recomendaciones con opinión",
      ],
    },
    painPoints: [
      "Salen demasiadas herramientas de IA cada semana. La señal es difícil de encontrar.",
      "La mayoría del contenido de IA es exageración o demasiado superficial para ser útil.",
      "Los desarrolladores necesitan casos de uso concretos, no notas de prensa.",
      "Los fundadores necesitan entender qué oportunidades vale la pena perseguir.",
      "Formadores y responsables técnicos necesitan mantenerse al día sin pasar horas cada día.",
    ],
    outcomes: [
      "Resumen mensual de desarrollo web con IA",
      "Actualizaciones de herramientas y opiniones honestas",
      "Ideas de flujo de trabajo de código",
      "Prompts prácticos",
      "Qué probar / ignorar este mes",
      "Recomendaciones con opinión",
    ],
    included: [
      { title: "Resumen mensual de desarrollo web con IA", description: "Un resumen seleccionado de lo que realmente importa en IA y desarrollo web este mes." },
      { title: "Actualizaciones de herramientas", description: "Opiniones honestas sobre nuevas herramientas de código con IA — qué cambió, qué vale la pena probar, qué es exageración." },
      { title: "Ideas de flujo de trabajo de código", description: "Patrones prácticos para integrar IA en proyectos React, Node.js y TypeScript." },
      { title: "Prompts prácticos", description: "Prompts probados para código, arquitectura y pensamiento de producto." },
      { title: "Qué probar / ignorar", description: "Una opinión directa sobre en qué invertir tiempo y qué saltarse este mes." },
      { title: "Recomendaciones con opinión", description: "Recomendaciones claras con razonamiento, no resúmenes." },
    ],
    pricing: [
      { label: "Muestra gratuita", price: "0 EUR" },
      { label: "Builder solo", price: "9 EUR / mes" },
      { label: "Builder pro", price: "19 EUR / mes", featured: true },
      { label: "Equipo / Escuela / Empresa", price: "99 EUR / mes" },
    ],
    faqs: [
      { question: "¿De qué trata esta newsletter?", answer: "Una actualización mensual práctica sobre IA generativa, herramientas de código, flujos de trabajo de desarrollo web, agentes de IA y oportunidades de producto." },
      { question: "¿Para quién es?", answer: "Desarrolladores, fundadores, freelancers, formadores y pequeños equipos técnicos." },
      { question: "¿Es apta para principiantes?", answer: "Sí. El tono es claro y práctico, con suficiente detalle para desarrolladores pero sin jerga innecesaria." },
      { question: "¿Incluirán fuentes?", answer: "Sí. Los números incluyen enlaces a fuentes e interpretación práctica, no solo resúmenes." },
      { question: "¿Puedo usarla para mi equipo?", answer: "Sí. El plan de equipo está hecho para compartir conocimiento internamente." },
      { question: "¿Puedo cancelar en cualquier momento?", answer: "Sí. No hay compromiso. Puedes cancelar en cualquier momento desde tu cuenta." },
    ],
  },
  'web-project-coaching': {
    title: "Coaching de Proyecto Web",
    meta: {
      title: "Coaching de Proyecto Web para Fundadores y Desarrolladores",
      description:
        "Coaching de desarrollo web individual y consultoría técnica para fundadores, freelancers y desarrolladores que construyen proyectos React, Node.js, TypeScript o asistidos por IA.",
    },
    badge: "Coaching",
    hero: {
      h1: "Desbloquea tu proyecto web con coaching técnico individual",
      subtitle:
        "Ayudo a fundadores, freelancers y desarrolladores a clarificar, depurar y estructurar proyectos web usando React, Node.js, TypeScript y flujos de desarrollo asistidos por IA.",
      primaryCta: "Reservar una sesión de coaching",
    },
    answer:
      "Coaching técnico individual y práctico para tu proyecto web. Trae un bloqueo, un bug, un código desordenado o un plan vago — y sal con un diagnóstico, un plan de acción y una comprensión clara de qué hacer a continuación. Adaptado a tu nivel, técnico o no.",
    useCases: [
      "Revisión de código",
      "Depuración",
      "Ayuda con React",
      "Ayuda con API Node",
      "Modelado de base de datos",
      "Despliegue",
      "Alcance de MVP",
      "Flujo de trabajo de código con IA",
      "Entender código generado",
    ],
    heroCard: {
      type: "checklist",
      title: "SALES CON",
      items: [
        "Un diagnóstico de proyecto claro",
        "Un plan de acción por escrito",
        "Consejos de arquitectura y stack",
        "Comprensión real de tu código",
        "Próximos pasos que puedes ejecutar",
      ],
    },
    painPoints: [
      "Estás bloqueado en tu proyecto y perdiendo tiempo.",
      "Código generado por IA que no entiendes del todo.",
      "Tu código está desordenado y no sabes por dónde empezar.",
      "Necesitas claridad técnica sin contratar a un desarrollador a tiempo completo.",
      "No sabes qué funcionalidad construir primero.",
      "Necesitas una opinión senior antes de gastar más dinero.",
    ],
    outcomes: [
      "Diagnóstico de proyecto",
      "Explicación clara",
      "Plan de acción",
      "Consejos de arquitectura",
      "Ayuda con depuración",
      "Próximos pasos por escrito",
    ],
    included: [
      { title: "Diagnóstico de proyecto", description: "Una lectura clara de tu código, arquitectura y la fuente real del problema." },
      { title: "Explicación técnica", description: "Un recorrido en lenguaje sencillo de qué está pasando y por qué." },
      { title: "Plan de acción", description: "Próximos pasos por escrito adaptados a tu proyecto y nivel." },
      { title: "Consejos de arquitectura", description: "Orientación práctica sobre estructura, patrones y compensaciones." },
      { title: "Ayuda con depuración", description: "Trabajo práctico en vivo sobre tu bloqueo específico." },
      { title: "Próximos pasos", description: "Un camino claro para que la sesión tenga un resultado definido." },
    ],
    pricing: [
      { label: "Coaching de 1 hora", price: "90 EUR" },
      { label: "Coaching de medio día", price: "300 EUR", featured: true },
      { label: "Coaching de día completo", price: "550 EUR" },
    ],
    faqs: [
      { question: "¿Necesito ser técnico?", answer: "No. La sesión puede adaptarse a fundadores no técnicos, principiantes o desarrolladores." },
      { question: "¿Puedes ayudar con código existente?", answer: "Sí, si puedes compartir el repositorio, capturas, errores o un contexto claro." },
      { question: "¿Puedes ayudar con código generado por IA?", answer: "Sí. Puedo ayudarte a entender, depurar y limpiar código generado por ChatGPT, Claude, Cursor o Copilot." },
      { question: "¿Esto es desarrollo o consultoría?", answer: "Puede incluir tanto orientación como ayuda técnica en vivo, pero no es trabajo de desarrollo ilimitado." },
      { question: "¿Qué debo preparar?", answer: "Una descripción de tu proyecto, tu objetivo, tu bloqueo y cualquier enlace o archivo útil." },
      { question: "¿Esto puede llevar a trabajo de desarrollo?", answer: "Sí. Si el alcance está claro, puedes pasar del coaching a jornadas de desarrollo o a un proyecto de MVP a medida." },
    ],
  },
  'full-stack-development-day': {
    title: "Jornada de Desarrollo Full-Stack",
    meta: {
      title: "Contrata un Desarrollador Full Stack React Node por un Día",
      description:
        "Reserva una sesión de desarrollo enfocada de medio día o día completo con un desarrollador full stack de React, Node.js y TypeScript para bugs, funcionalidades, dashboards, APIs y avance de MVP.",
    },
    badge: "Entrega",
    hero: {
      h1: "Reserva una jornada de desarrollo full-stack enfocada para tu proyecto web",
      subtitle:
        "¿Necesitas una funcionalidad, corrección de bug, dashboard, API o limpieza técnica? Trabajo en tu proyecto React, Node.js o TypeScript en bloques enfocados de medio día o día completo.",
      primaryCta: "Solicitar un espacio de desarrollo",
    },
    answer:
      "Tiempo de desarrollo profesional y enfocado en tu base de código existente — reservado por medio día o día completo. No es la construcción de un producto completo: un bloque dedicado para una funcionalidad, bug, dashboard o refactor específico, entregado con notas sobre lo que cambió y qué sigue.",
    useCases: [
      "Páginas React",
      "Componentes Next.js",
      "APIs Node",
      "Trabajo con PostgreSQL",
      "Flujos de autenticación",
      "Dashboards",
      "Paneles de administración",
      "Refactorización",
      "Integraciones de API de IA",
      "Correcciones de despliegue",
      "Mejoras de UI",
      "Diseños responsivos",
    ],
    heroCard: {
      type: "info",
      title: "QUÉ ES ESTO",
      description:
        "Tiempo de desarrollo profesional y enfocado en tu base de código existente — reservado por medio día o día completo. No es la construcción de un producto completo: un bloque dedicado para entregar una funcionalidad específica, corregir un bug o lograr un resultado técnico claro.",
      whenTitle: "CUÁNDO USARLO",
      whenItems: [
        "Tienes una funcionalidad o bug acotado pero sin capacidad de desarrollo",
        "Necesitas un par de manos senior durante unos días",
        "Quieres un refactor enfocado o una limpieza técnica",
        "Necesitas que se entregue una porción funcional en un plazo ajustado",
      ],
      leaveWithItems: [
        "Una funcionalidad, corrección o refactor entregado",
        "Notas de entrega con las decisiones tomadas",
        "Próximos pasos claros documentados",
        "Código funcional del que eres totalmente propietario",
      ],
    },
    painPoints: [
      "Tienes un bug o funcionalidad clara pero sin tiempo de desarrollador para abordarlo.",
      "Necesitas avance rápido y fiable sin un proceso largo de contratación.",
      "Tu proyecto está atascado en una tarea específica y necesita un desarrollador autónomo.",
      "Necesitas revisión de código, refactorización o una limpieza técnica.",
      "Necesitas que una funcionalidad o integración se entregue en un calendario definido.",
    ],
    outcomes: [
      "Funcionalidad o corrección de bug acotada entregada",
      "Notas de entrega con decisiones tomadas",
      "Próximos pasos claros documentados",
      "Código funcional del que eres propietario",
    ],
    included: [
      { title: "Trabajo en React y Next.js", description: "Páginas, layouts, dashboards y componentes de UI interactivos." },
      { title: "APIs de Node.js", description: "Endpoints REST, rutas Express, modelado de datos e integraciones con terceros." },
      { title: "Trabajo de base de datos", description: "Esquema PostgreSQL, consultas, migraciones y limpieza de datos." },
      { title: "Flujos de autenticación", description: "Gestión de sesiones, JWT, OAuth2 o autenticación basada en proveedor." },
      { title: "Corrección de bugs", description: "Diagnóstico y resolución de bugs de producción con pasos de reproducción." },
      { title: "Notas de entrega", description: "Un resumen escrito de lo que se hizo, decisiones tomadas y qué sigue." },
    ],
    pricing: [
      { label: "Medio día", price: "350 EUR" },
      { label: "Día completo", price: "600 EUR", featured: true },
      { label: "Paquete de 3 días", price: "1650 EUR" },
      { label: "Paquete de 5 días", price: "2600 EUR" },
      { label: "Paquete de 10 días", price: "5000 EUR" },
    ],
    goodFit: [
      "Bug o funcionalidad clara con una definición de \"terminado\"",
      "Base de código existente con instrucciones de configuración",
      "Necesidad de avance rápido y enfocado",
      "Necesidad de un desarrollador autónomo",
      "Trabajo de revisión de código, refactorización o limpieza",
    ],
    notAFit: [
      "Un MVP completo construido en un día",
      "Sin acceso al repositorio ni documentación de configuración",
      "Sin tarea clara ni definición de \"terminado\"",
      "Alcance poco realista para el tiempo reservado",
    ],
    processSteps: [
      { title: "Envía la tarea", description: "Describe la tarea, cómo se ve \"terminado\", y comparte el repositorio y cualquier contexto relevante." },
      { title: "Validación del alcance", description: "Confirmo que la tarea es realista para la duración de la sesión y aclaro cualquier bloqueo antes de empezar." },
      { title: "Sesión de desarrollo enfocada", description: "Trabajo en tu proyecto en un bloque dedicado sin interrupciones." },
      { title: "Recibe las notas de entrega", description: "Un resumen escrito de lo que se hizo, qué cambió y qué sigue." },
      { title: "Sesión siguiente opcional", description: "Si el alcance necesita más tiempo, programamos un seguimiento con una tarea refinada." },
    ],
    faqs: [
      { question: "¿Puedes construir una app completa en un día?", answer: "No. Una app completa requiere un proyecto a medida. Este servicio es para trabajo de desarrollo enfocado en una tarea específica." },
      { question: "¿Con qué tecnologías trabajas?", answer: "React, Next.js, TypeScript, Node.js, Express, PostgreSQL, Docker y herramientas web modernas." },
      { question: "¿Puedes trabajar en una base de código existente?", answer: "Sí, si el repositorio y las instrucciones de configuración están claros." },
      { question: "¿Puedes corregir bugs?", answer: "Sí, si proporcionas suficiente contexto, pasos de reproducción y acceso." },
      { question: "¿Puedes integrar APIs de IA?", answer: "Sí. Puedo ayudar con la API de OpenAI, flujos de trabajo asistidos por IA y funcionalidades simples potenciadas por IA." },
      { question: "¿Explicarás qué cambiaste?", answer: "Sí. Las notas de entrega resumen lo que se hizo y qué sigue." },
    ],
  },
  'mvp-bootstrapping-workshop': {
    title: "Taller AI Clarity Bootstrap",
    meta: {
      title: "Framework AI Clarity — Taller de MVP para Fundadores Solitarios",
      description:
        "Un taller práctico para clarificar tu idea de aplicación web, definir tu MVP, elegir el stack adecuado y crear una hoja de ruta realista usando el framework AI Clarity — para fundadores solitarios y equipos pequeños.",
    },
    badge: "Taller",
    hero: {
      h1: "Convierte tu idea de aplicación web en un plan de MVP realista",
      subtitle:
        "Un taller práctico para fundadores y builders que necesitan clarificar su producto, definir la primera versión y entender qué se necesitará para construirla.",
      primaryCta: "Reservar el taller",
    },
    answer:
      "Una sesión de trabajo estructurada que convierte una idea difusa en un plan construible: alcance de MVP, prioridades de funcionalidades, flujos de usuario, stack tecnológico, hoja de ruta y un presupuesto realista. No se escribe código — el entregable es claridad, para que dejes de adivinar y empieces a construir lo correcto.",
    useCases: [],
    heroCard: {
      type: "checklist",
      title: "SALES CON",
      items: [
        "Un alcance de MVP definido",
        "Una lista de funcionalidades priorizada",
        "Un stack tecnológico y hoja de ruta",
        "Una estimación de presupuesto realista",
      ],
    },
    painPoints: [
      "Tienes una idea pero ningún plan claro de qué construir.",
      "No sabes qué funcionalidades priorizar.",
      "Corres el riesgo de perder tiempo y dinero construyendo el producto equivocado.",
      "No puedes comunicar tu idea claramente a los desarrolladores.",
      "Quieres usar IA en tu producto pero no sabes dónde aporta valor.",
    ],
    outcomes: [
      "Alcance de MVP definido",
      "Prioridades de funcionalidades clasificadas",
      "Stack tecnológico recomendado",
      "Hoja de ruta de desarrollo creada",
      "Estimación de presupuesto proporcionada",
      "Mapa de riesgos documentado",
    ],
    included: [
      { title: "Alcance de MVP", description: "Una lista definida de qué construir y qué aplazar para la primera versión." },
      { title: "Prioridades de funcionalidades", description: "Una lista de funcionalidades clasificada por impacto, riesgo y esfuerzo de construcción." },
      { title: "Recomendación de stack tecnológico", description: "Un stack práctico ajustado a tu equipo, calendario y necesidades de producto." },
      { title: "Hoja de ruta de desarrollo", description: "Un plan por fases con hitos y estimaciones de entrega realistas." },
      { title: "Estimación de presupuesto", description: "Un rango de coste aproximado basado en alcance, complejidad y calendario." },
      { title: "Mapa de riesgos", description: "Riesgos conocidos, suposiciones y cómo reducir la incertidumbre antes de construir." },
    ],
    pricing: [
      { label: "Taller de Claridad MVP de 1 día", price: "650 EUR" },
      { label: "Sprint de MVP de 5 días", price: "2800 EUR", featured: true },
      { label: "Sprint Premium de 5 días + prototipo / spec", price: "3500 EUR" },
    ],
    goodFit: [
      "Fundadores no técnicos con una idea de producto",
      "Freelancers y creadores construyendo un producto digital",
      "Indie hackers planeando un SaaS o herramienta",
      "Proyectos en fase inicial sin una especificación técnica",
      "Pequeñas empresas que necesitan un plan de producto realista",
    ],
    notAFit: [
      "Ya tienes una especificación técnica detallada",
      "Necesitas desarrollo, no planificación",
      "Tienes un equipo técnico interno completo",
      "Necesitas un plan de marketing o negocio, no una hoja de ruta de producto",
    ],
    faqs: [
      { question: "¿Necesito conocimientos técnicos?", answer: "No. Este taller está diseñado para hacer comprensibles las decisiones técnicas." },
      { question: "¿Necesito un proyecto existente?", answer: "No. Puedes venir solo con una idea o un concepto aproximado." },
      { question: "¿Construirás el MVP durante el taller?", answer: "No. El taller crea el plan, la hoja de ruta y el alcance. El desarrollo es un servicio separado." },
      { question: "¿Cuál es la diferencia entre 1 día y 5 días?", answer: "El taller de 1 día aporta claridad y una hoja de ruta. El sprint de 5 días profundiza en especificaciones, arquitectura, flujos de usuario y planificación de entrega." },
      { question: "¿Este taller puede llevar a un MVP completo?", answer: "Sí. Si el alcance es realista, puede convertirse en un proyecto de desarrollo a medida." },
      { question: "¿Puedes incluir funcionalidades de IA en la hoja de ruta?", answer: "Sí. Las funcionalidades de IA pueden evaluarse según su utilidad, complejidad y coste." },
    ],
  },
  'mvp-development': {
    title: "Desarrollo de MVP a Medida",
    meta: {
      title: "Desarrollo de MVP para Aplicaciones Web y Productos SaaS",
      description:
        "Desarrollo de MVP a medida para fundadores y equipos pequeños. Construye una aplicación web React, Node.js y TypeScript desde el alcance de producto hasta el despliegue.",
    },
    badge: "MVP",
    hero: {
      h1: "Construye tu MVP con un desarrollador full-stack que también te ayuda a pensar el producto",
      subtitle:
        "Ayudo a fundadores y equipos pequeños a convertir una idea de producto clara en una aplicación web funcional usando React, Node.js, TypeScript y flujos de desarrollo asistidos por IA prácticos.",
      primaryCta: "Solicitar un presupuesto",
    },
    answer:
      "Desarrollo de principio a fin de una primera versión de tu aplicación web — desde la clarificación de producto y arquitectura hasta el frontend, backend, base de datos, despliegue y entrega. Construido por un único desarrollador full-stack que también puede ayudarte a tomar decisiones de producto, para que el alcance se mantenga razonable y la primera versión realmente se entregue.",
    useCases: [
      "MVPs de SaaS",
      "Herramientas internas",
      "Dashboards",
      "Marketplaces simples",
      "Herramientas asistidas por IA",
      "Paneles de administración",
      "Plataformas de automatización",
      "Herramientas de productividad",
      "Portales de clientes",
      "Plataformas de formación",
    ],
    heroCard: {
      type: "info",
      title: "QUÉ ES ESTO",
      description:
        "Desarrollo de principio a fin de la primera versión de tu aplicación web — clarificación de producto, arquitectura, frontend, backend, despliegue y entrega, realizado por un único desarrollador full-stack que también puede ayudarte a tomar decisiones de producto.",
      whenTitle: "CUÁNDO USARLO",
      whenItems: [
        "Tienes una idea de producto clara y necesitas entregar la primera versión",
        "No puedes permitirte o no necesitas todavía un equipo completo",
        "Quieres pensamiento de producto y ejecución de la misma persona",
        "Quieres lanzar rápido sin acumular deuda técnica",
      ],
      leaveWithItems: [
        "Una aplicación web funcional en producción",
        "Alcance de producto clarificado en el camino",
        "Base de código entregada con documentación",
        "Bases listas para la siguiente fase",
      ],
    },
    painPoints: [
      "Tienes una idea de producto clara pero ningún equipo técnico para construirla.",
      "No puedes permitirte un equipo de desarrollo a tiempo completo para un producto no validado.",
      "No sabes cómo definir el alcance, diseñar la arquitectura y entregar una primera versión realista.",
      "Necesitas a alguien que pueda tanto pensar el producto como construirlo.",
      "Quieres lanzar rápido sin construir una deuda técnica de la que te arrepentirás.",
    ],
    outcomes: [
      "Aplicación web funcional entregada",
      "Clarificación de producto incluida",
      "Despliegue completo gestionado",
      "Entrega de base de código con documentación",
    ],
    included: [
      { title: "Clarificación de producto", description: "Sesiones de descubrimiento para alinear alcance, prioridades y criterios de éxito." },
      { title: "Arquitectura técnica", description: "Diseño de sistema, modelos de datos, contratos de API y plan de infraestructura." },
      { title: "Frontend", description: "UI en React o Next.js construida según tu estructura de producto y dirección de diseño." },
      { title: "Backend", description: "API de Node.js con Express, autenticación, lógica de negocio e integraciones." },
      { title: "Base de datos", description: "Diseño de esquema PostgreSQL o Supabase, migraciones y optimización de consultas." },
      { title: "Despliegue y entrega", description: "Despliegue en producción en Cloudflare Pages, Vercel o tu hosting preferido, más documentación completa de la base de código." },
    ],
    pricing: [{ label: "Desarrollo de MVP a medida", price: "desde 4500 EUR", featured: true }],
    pricingNote:
      "Rango típico: 6000 EUR – 15 000 EUR según el alcance. Presupuesto a medida proporcionado tras una llamada de descubrimiento.",
    goodFit: [
      "Tienes un problema claro que resolver",
      "Puedes priorizar y reducir el alcance",
      "Tienes un presupuesto realista",
      "Quieres una primera versión limpia y desplegable",
      "Estás abierto a un enfoque de MVP por etapas",
    ],
    notAFit: [
      "Quieres un marketplace complejo o red social en dos semanas",
      "No tienes presupuesto o te niegas a discutir el alcance",
      "Esperas funcionalidades ilimitadas a precio fijo",
      "Buscas acuerdos solo de participación accionaria",
    ],
    processSteps: [
      { title: "Descubrimiento", description: "Mapeo contigo la idea de producto, usuarios objetivo, funcionalidades imprescindibles, restricciones y riesgos." },
      { title: "Alcance y propuesta", description: "Escribo un documento de alcance claro con hitos, calendario y una propuesta de precio fijo." },
      { title: "Sprint de construcción", description: "El desarrollo ocurre en sprints enfocados con puntos de control y actualizaciones de progreso regulares." },
      { title: "Revisión", description: "Pruebas el producto funcional y das tu opinión antes de la entrega final." },
      { title: "Despliegue y entrega", description: "El producto se despliega en producción y se entrega con documentación completa." },
    ],
    faqs: [
      { question: "¿Cuánto cuesta un MVP?", answer: "El desarrollo de MVP empieza en 4500 EUR. La mayoría de los proyectos van entre 6000 EUR y 15 000 EUR según el alcance." },
      { question: "¿Cuánto tiempo lleva?", answer: "Depende del alcance. Un MVP pequeño puede llevar unas semanas. Un MVP más complejo necesita una hoja de ruta por etapas." },
      { question: "¿Puedes ayudar a definir el alcance primero?", answer: "Sí. El Taller AI Clarity Bootstrap se recomienda antes del desarrollo si la idea aún no está clara." },
      { question: "¿Puedes incluir funcionalidades de IA?", answer: "Sí, si son útiles y realistas para la primera versión." },
      { question: "¿Te encargas del despliegue?", answer: "Sí. El despliegue y la entrega están incluidos." },
      { question: "¿Puedes trabajar con una base de código existente?", answer: "Sí, tras revisión. Los proyectos existentes pueden requerir una auditoría primero." },
      { question: "¿Proporcionas diseño?", answer: "Puedo crear estructuras de UI de producto limpias, pero una marca avanzada o identidad visual a medida puede requerir un diseñador dedicado." },
      { question: "¿Qué pasa después del lanzamiento?", answer: "Puedes reservar jornadas de desarrollo, soporte, mejoras o un nuevo sprint." },
    ],
  },
};
