import type { ServiceContent } from './en';

export const servicesContentFr: Record<string, ServiceContent> = {
  'ai-web-development-newsletter': {
    title: "Newsletter Développement Web IA",
    meta: {
      title: "Newsletter Développement Web IA pour Développeurs et Fondateurs",
      description:
        "Une newsletter mensuelle sur l'IA générative, les outils de code, les agents IA et les workflows pratiques de développement web pour développeurs, fondateurs et freelances.",
    },
    badge: "Newsletter",
    hero: {
      h1: "Restez à la pointe du développement web IA sans perdre des heures dans le bruit",
      subtitle:
        "Une newsletter mensuelle concrète pour développeurs, fondateurs et freelances qui veulent comprendre ce qui compte en IA générative, outils de code et développement web assisté par IA.",
      primaryCta: "Rejoindre la liste d'attente",
    },
    answer:
      "Un briefing mensuel concret sur ce qui compte vraiment en IA générative, outils de code et développement web. Sélectionné pour les développeurs, fondateurs et freelances qui veulent prendre de bonnes décisions sans tout lire.",
    useCases: [],
    heroCard: {
      type: "checklist",
      title: "CHAQUE NUMÉRO INCLUT",
      items: [
        "Les outils IA qui valent le coup d'être testés ce mois-ci",
        "Des idées de workflow de code",
        "Des prompts concrets",
        "Ce qu'il faut ignorer",
        "Des recommandations tranchées",
      ],
    },
    painPoints: [
      "Trop d'outils IA sortent chaque semaine. Le signal est difficile à trouver.",
      "La plupart du contenu IA est du battage médiatique ou trop superficiel pour être utile.",
      "Les développeurs ont besoin de cas d'usage concrets, pas de communiqués de presse.",
      "Les fondateurs doivent comprendre quelles opportunités valent la peine d'être poursuivies.",
      "Formateurs et référents techniques doivent rester à jour sans y passer des heures chaque jour.",
    ],
    outcomes: [
      "Briefing mensuel dev web IA",
      "Mises à jour d'outils et avis honnêtes",
      "Idées de workflow de code",
      "Prompts concrets",
      "À tester / à ignorer ce mois-ci",
      "Recommandations tranchées",
    ],
    included: [
      { title: "Briefing mensuel dev web IA", description: "Un résumé sélectionné de ce qui compte vraiment en IA et développement web ce mois-ci." },
      { title: "Mises à jour d'outils", description: "Des avis honnêtes sur les nouveaux outils de code IA — ce qui a changé, ce qui vaut le coup, ce qui est du battage médiatique." },
      { title: "Idées de workflow de code", description: "Des patterns concrets pour intégrer l'IA dans des projets React, Node.js et TypeScript." },
      { title: "Prompts concrets", description: "Des prompts testés pour le code, l'architecture et la réflexion produit." },
      { title: "À tester / à ignorer", description: "Un avis direct sur où passer du temps et quoi éviter ce mois-ci." },
      { title: "Recommandations tranchées", description: "Des recommandations claires avec un raisonnement, pas des résumés." },
    ],
    pricing: [
      { label: "Échantillon gratuit", price: "0 EUR" },
      { label: "Builder solo", price: "9 EUR / mois" },
      { label: "Builder pro", price: "19 EUR / mois", featured: true },
      { label: "Équipe / École / Entreprise", price: "99 EUR / mois" },
    ],
    faqs: [
      { question: "De quoi parle cette newsletter ?", answer: "Une mise à jour mensuelle concrète sur l'IA générative, les outils de code, les workflows de développement web, les agents IA et les opportunités produit." },
      { question: "À qui s'adresse-t-elle ?", answer: "Développeurs, fondateurs, freelances, formateurs et petites équipes techniques." },
      { question: "Est-elle accessible aux débutants ?", answer: "Oui. Le ton est clair et concret, avec assez de détails pour les développeurs mais sans jargon inutile." },
      { question: "Inclurez-vous des sources ?", answer: "Oui. Les numéros incluent des liens sources et une interprétation concrète, pas seulement des résumés." },
      { question: "Puis-je l'utiliser pour mon équipe ?", answer: "Oui. Le forfait équipe est fait pour le partage de connaissances en interne." },
      { question: "Puis-je annuler à tout moment ?", answer: "Oui. Il n'y a aucun engagement. Vous pouvez annuler à tout moment depuis votre compte." },
    ],
  },
  'web-project-coaching': {
    title: "Coaching Projet Web",
    meta: {
      title: "Coaching Projet Web pour Fondateurs et Développeurs",
      description:
        "Coaching de développement web individuel et conseil technique pour fondateurs, freelances et développeurs qui construisent des projets React, Node.js, TypeScript ou assistés par IA.",
    },
    badge: "Coaching",
    hero: {
      h1: "Débloquez votre projet web avec un coaching technique individuel",
      subtitle:
        "J'aide fondateurs, freelances et développeurs à clarifier, déboguer et structurer des projets web avec React, Node.js, TypeScript et des workflows de développement assisté par IA.",
      primaryCta: "Réserver une session de coaching",
    },
    answer:
      "Un coaching technique individuel et concret pour votre projet web. Apportez un blocage, un bug, un code désordonné ou un plan flou — et repartez avec un diagnostic, un plan d'action et une compréhension claire de la prochaine étape. Adapté à votre niveau, technique ou non.",
    useCases: [
      "Revue de code",
      "Débogage",
      "Aide React",
      "Aide API Node",
      "Modélisation de base de données",
      "Déploiement",
      "Cadrage MVP",
      "Workflow de code IA",
      "Comprendre du code généré",
    ],
    heroCard: {
      type: "checklist",
      title: "VOUS REPARTEZ AVEC",
      items: [
        "Un diagnostic de projet clair",
        "Un plan d'action écrit",
        "Des conseils d'architecture et de stack",
        "Une vraie compréhension de votre code",
        "Des prochaines étapes exécutables",
      ],
    },
    painPoints: [
      "Vous êtes bloqué sur votre projet et vous perdez du temps.",
      "Du code généré par IA que vous ne comprenez pas totalement.",
      "Votre code est désordonné et vous ne savez pas par où commencer.",
      "Vous avez besoin de clarté technique sans embaucher un développeur à temps plein.",
      "Vous ne savez pas quelle fonctionnalité construire en premier.",
      "Vous avez besoin d'un avis senior avant de dépenser plus d'argent.",
    ],
    outcomes: [
      "Diagnostic de projet",
      "Explication claire",
      "Plan d'action",
      "Conseils d'architecture",
      "Aide au débogage",
      "Prochaines étapes écrites",
    ],
    included: [
      { title: "Diagnostic de projet", description: "Une lecture claire de votre code, votre architecture et la vraie source du problème." },
      { title: "Explication technique", description: "Un tour d'horizon en langage clair de ce qui se passe et pourquoi." },
      { title: "Plan d'action", description: "Des prochaines étapes écrites, adaptées à votre projet et votre niveau." },
      { title: "Conseils d'architecture", description: "Des conseils concrets sur la structure, les patterns et les compromis." },
      { title: "Aide au débogage", description: "Un travail pratique en direct sur votre blocage spécifique." },
      { title: "Prochaines étapes", description: "Un chemin clair pour que la session ait un résultat défini." },
    ],
    pricing: [
      { label: "Coaching 1 heure", price: "90 EUR" },
      { label: "Coaching demi-journée", price: "300 EUR", featured: true },
      { label: "Coaching journée complète", price: "550 EUR" },
    ],
    faqs: [
      { question: "Dois-je être technique ?", answer: "Non. La session peut être adaptée aux fondateurs non techniques, débutants ou développeurs." },
      { question: "Pouvez-vous aider sur du code existant ?", answer: "Oui, si vous pouvez partager le repo, des captures, des erreurs ou un contexte clair." },
      { question: "Pouvez-vous aider avec du code généré par IA ?", answer: "Oui. Je peux vous aider à comprendre, déboguer et nettoyer du code généré par ChatGPT, Claude, Cursor ou Copilot." },
      { question: "Est-ce du développement ou du conseil ?", answer: "Cela peut inclure à la fois des conseils et de l'aide technique en direct, mais ce n'est pas du développement illimité." },
      { question: "Que dois-je préparer ?", answer: "Une description de votre projet, votre objectif, votre blocage et tout lien ou fichier utile." },
      { question: "Cela peut-il mener à du développement ?", answer: "Oui. Si le périmètre est clair, vous pouvez passer du coaching à des journées de développement ou un projet MVP sur mesure." },
    ],
  },
  'full-stack-development-day': {
    title: "Journée de Développement Full-Stack",
    meta: {
      title: "Engagez un Développeur Full Stack React Node pour une Journée",
      description:
        "Réservez une session de développement ciblée d'une demi-journée ou d'une journée avec un développeur full stack React, Node.js et TypeScript pour des bugs, fonctionnalités, dashboards, API et avancement de MVP.",
    },
    badge: "Livraison",
    hero: {
      h1: "Réservez une journée de développement full-stack ciblée pour votre projet web",
      subtitle:
        "Besoin d'une fonctionnalité, d'un correctif, d'un dashboard, d'une API ou d'un nettoyage technique ? Je travaille sur votre projet React, Node.js ou TypeScript par blocs ciblés d'une demi-journée ou d'une journée.",
      primaryCta: "Demander un créneau de développement",
    },
    answer:
      "Du temps de développement professionnel et ciblé sur votre code existant — réservé à la demi-journée ou à la journée. Pas une construction de produit complet : un bloc dédié pour une fonctionnalité, un bug, un dashboard ou un refactor spécifique, livré avec des notes sur ce qui a changé et la suite.",
    useCases: [
      "Pages React",
      "Composants Next.js",
      "API Node",
      "Travail PostgreSQL",
      "Flux d'authentification",
      "Dashboards",
      "Panneaux d'administration",
      "Refactoring",
      "Intégrations d'API IA",
      "Corrections de déploiement",
      "Améliorations UI",
      "Mises en page responsives",
    ],
    heroCard: {
      type: "info",
      title: "CE QUE C'EST",
      description:
        "Du temps de développement professionnel et ciblé sur votre code existant — réservé à la demi-journée ou à la journée. Pas une construction de produit complet : un bloc dédié pour livrer une fonctionnalité spécifique, corriger un bug ou obtenir un résultat technique clair.",
      whenTitle: "QUAND L'UTILISER",
      whenItems: [
        "Vous avez une fonctionnalité ou un bug cadré mais pas de disponibilité dev",
        "Vous avez besoin d'une paire de mains senior pour quelques jours",
        "Vous voulez un refactor ciblé ou un nettoyage technique",
        "Vous avez besoin qu'une tranche fonctionnelle soit livrée dans un délai serré",
      ],
      leaveWithItems: [
        "Une fonctionnalité, un correctif ou un refactor livré",
        "Des notes de livraison avec les décisions prises",
        "Des prochaines étapes claires documentées",
        "Du code fonctionnel dont vous êtes pleinement propriétaire",
      ],
    },
    painPoints: [
      "Vous avez un bug ou une fonctionnalité clairs mais pas de temps développeur pour vous y attaquer.",
      "Vous avez besoin d'un avancement rapide et fiable sans long processus d'embauche.",
      "Votre projet est bloqué sur une tâche spécifique et a besoin d'un développeur autonome.",
      "Vous avez besoin d'une revue de code, d'un refactoring ou d'un nettoyage technique.",
      "Vous avez besoin qu'une fonctionnalité ou une intégration soit livrée selon un calendrier défini.",
    ],
    outcomes: [
      "Fonctionnalité ou correctif cadré livré",
      "Notes de livraison avec décisions prises",
      "Prochaines étapes claires documentées",
      "Code fonctionnel dont vous êtes propriétaire",
    ],
    included: [
      { title: "Travail React et Next.js", description: "Pages, layouts, dashboards et composants UI interactifs." },
      { title: "API Node.js", description: "Endpoints REST, routes Express, modélisation de données et intégrations tierces." },
      { title: "Travail base de données", description: "Schéma PostgreSQL, requêtes, migrations et nettoyage de données." },
      { title: "Flux d'authentification", description: "Gestion de session, JWT, OAuth2 ou authentification par fournisseur." },
      { title: "Correction de bugs", description: "Diagnostic et résolution de bugs de production avec étapes de reproduction." },
      { title: "Notes de livraison", description: "Un résumé écrit de ce qui a été fait, des décisions prises et de la suite." },
    ],
    pricing: [
      { label: "Demi-journée", price: "350 EUR" },
      { label: "Journée complète", price: "600 EUR", featured: true },
      { label: "Pack 3 jours", price: "1 650 EUR" },
      { label: "Pack 5 jours", price: "2 600 EUR" },
      { label: "Pack 10 jours", price: "5 000 EUR" },
    ],
    goodFit: [
      "Bug ou fonctionnalité clair avec une définition du « terminé »",
      "Code existant avec instructions d'installation",
      "Besoin d'avancement rapide et ciblé",
      "Besoin d'un développeur autonome",
      "Travail de revue de code, refactoring ou nettoyage",
    ],
    notAFit: [
      "Un MVP complet construit en une journée",
      "Aucun accès au repository ni documentation d'installation",
      "Aucune tâche claire ni définition du « terminé »",
      "Un périmètre irréaliste pour le temps réservé",
    ],
    processSteps: [
      { title: "Envoyez la tâche", description: "Décrivez la tâche, à quoi ressemble le « terminé », et partagez le repo et tout contexte utile." },
      { title: "Validation du périmètre", description: "Je confirme que la tâche est réaliste pour la durée de la session et clarifie les blocages avant de commencer." },
      { title: "Session de développement ciblée", description: "Je travaille sur votre projet dans un bloc dédié sans interruption." },
      { title: "Réception des notes de livraison", description: "Un résumé écrit de ce qui a été fait, ce qui a changé et la suite." },
      { title: "Session suivante optionnelle", description: "Si le périmètre nécessite plus de temps, nous planifions un suivi avec une tâche affinée." },
    ],
    faqs: [
      { question: "Pouvez-vous construire une app complète en une journée ?", answer: "Non. Une app complète nécessite un projet sur mesure. Ce service est pour du développement ciblé sur une tâche spécifique." },
      { question: "Avec quelles technologies travaillez-vous ?", answer: "React, Next.js, TypeScript, Node.js, Express, PostgreSQL, Docker et les outils web modernes." },
      { question: "Pouvez-vous travailler sur du code existant ?", answer: "Oui, si le repository et les instructions d'installation sont clairs." },
      { question: "Pouvez-vous corriger des bugs ?", answer: "Oui, si vous fournissez suffisamment de contexte, d'étapes de reproduction et d'accès." },
      { question: "Pouvez-vous intégrer des API IA ?", answer: "Oui. Je peux aider avec l'API OpenAI, les workflows assistés par IA et des fonctionnalités simples propulsées par IA." },
      { question: "Expliquerez-vous ce que vous avez changé ?", answer: "Oui. Les notes de livraison résument ce qui a été fait et la suite." },
    ],
  },
  'mvp-bootstrapping-workshop': {
    title: "Atelier AI Clarity Bootstrap",
    meta: {
      title: "Framework AI Clarity — Atelier MVP pour Fondateurs Solo",
      description:
        "Un atelier concret pour clarifier votre idée d'application web, définir votre MVP, choisir la bonne stack et créer une feuille de route réaliste avec le framework AI Clarity — pour fondateurs solo et petites équipes.",
    },
    badge: "Atelier",
    hero: {
      h1: "Transformez votre idée d'application web en un plan MVP réaliste",
      subtitle:
        "Un atelier concret pour fondateurs et builders qui doivent clarifier leur produit, définir la première version et comprendre ce qu'il faudra pour la construire.",
      primaryCta: "Réserver l'atelier",
    },
    answer:
      "Une session de travail structurée qui transforme une idée floue en plan constructible : cadrage MVP, priorités de fonctionnalités, parcours utilisateurs, stack technique, feuille de route et budget réaliste. Aucun code n'est écrit — le livrable est la clarté, pour que vous arrêtiez de deviner et commenciez à construire la bonne chose.",
    useCases: [],
    heroCard: {
      type: "checklist",
      title: "VOUS REPARTEZ AVEC",
      items: [
        "Un périmètre MVP défini",
        "Une liste de fonctionnalités priorisées",
        "Une stack technique et une feuille de route",
        "Une estimation de budget réaliste",
      ],
    },
    painPoints: [
      "Vous avez une idée mais aucun plan clair de ce qu'il faut construire.",
      "Vous ne savez pas quelles fonctionnalités prioriser.",
      "Vous risquez de perdre du temps et de l'argent à construire le mauvais produit.",
      "Vous n'arrivez pas à communiquer clairement votre idée aux développeurs.",
      "Vous voulez utiliser l'IA dans votre produit mais ne savez pas où elle apporte de la valeur.",
    ],
    outcomes: [
      "Périmètre MVP défini",
      "Priorités de fonctionnalités classées",
      "Stack technique recommandée",
      "Feuille de route de développement créée",
      "Estimation de budget fournie",
      "Carte des risques documentée",
    ],
    included: [
      { title: "Périmètre MVP", description: "Une liste définie de ce qu'il faut construire et reporter pour la première version." },
      { title: "Priorités de fonctionnalités", description: "Une liste de fonctionnalités classée par impact, risque et effort de construction." },
      { title: "Recommandation de stack technique", description: "Une stack concrète adaptée à votre équipe, votre calendrier et vos besoins produit." },
      { title: "Feuille de route de développement", description: "Un plan par phases avec jalons et estimations de livraison réalistes." },
      { title: "Estimation de budget", description: "Une fourchette de coût approximative basée sur le périmètre, la complexité et le calendrier." },
      { title: "Carte des risques", description: "Risques connus, hypothèses et comment réduire l'incertitude avant de construire." },
    ],
    pricing: [
      { label: "Atelier Clarity MVP 1 jour", price: "650 EUR" },
      { label: "Sprint MVP 5 jours", price: "2 800 EUR", featured: true },
      { label: "Sprint Premium 5 jours + prototype / spec", price: "3 500 EUR" },
    ],
    goodFit: [
      "Fondateurs non techniques avec une idée de produit",
      "Freelances et créateurs construisant un produit numérique",
      "Indie hackers planifiant un SaaS ou un outil",
      "Projets en phase initiale sans spécification technique",
      "Petites entreprises ayant besoin d'un plan produit réaliste",
    ],
    notAFit: [
      "Vous avez déjà une spécification technique détaillée",
      "Vous avez besoin de développement, pas de planification",
      "Vous avez une équipe technique interne complète",
      "Vous avez besoin d'un plan marketing ou business, pas d'une feuille de route produit",
    ],
    faqs: [
      { question: "Ai-je besoin d'un bagage technique ?", answer: "Non. Cet atelier est conçu pour rendre les choix techniques compréhensibles." },
      { question: "Ai-je besoin d'un projet existant ?", answer: "Non. Vous pouvez venir avec seulement une idée ou un concept approximatif." },
      { question: "Construirez-vous le MVP pendant l'atelier ?", answer: "Non. L'atelier crée le plan, la feuille de route et le périmètre. Le développement est un service séparé." },
      { question: "Quelle est la différence entre 1 jour et 5 jours ?", answer: "L'atelier d'1 jour apporte clarté et feuille de route. Le sprint de 5 jours approfondit les spécifications, l'architecture, les parcours utilisateurs et la planification de livraison." },
      { question: "Cet atelier peut-il mener à un MVP complet ?", answer: "Oui. Si le périmètre est réaliste, il peut devenir un projet de développement sur mesure." },
      { question: "Pouvez-vous inclure des fonctionnalités IA dans la feuille de route ?", answer: "Oui. Les fonctionnalités IA peuvent être évaluées selon leur utilité, complexité et coût." },
    ],
  },
  'mvp-development': {
    title: "Développement MVP Sur Mesure",
    meta: {
      title: "Développement MVP pour Applications Web et Produits SaaS",
      description:
        "Développement MVP sur mesure pour fondateurs et petites équipes. Construisez une application web React, Node.js et TypeScript du cadrage produit au déploiement.",
    },
    badge: "MVP",
    hero: {
      h1: "Construisez votre MVP avec un développeur full-stack qui vous aide aussi à réfléchir au produit",
      subtitle:
        "J'aide fondateurs et petites équipes à transformer une idée de produit claire en application web fonctionnelle avec React, Node.js, TypeScript et des workflows de développement assisté par IA concrets.",
      primaryCta: "Demander un devis",
    },
    answer:
      "Développement de bout en bout d'une première version de votre application web — de la clarification produit et de l'architecture au frontend, backend, base de données, déploiement et passation. Construit par un seul développeur full-stack qui peut aussi vous aider à prendre des décisions produit, pour que le périmètre reste raisonnable et que la première version soit réellement livrée.",
    useCases: [
      "MVP SaaS",
      "Outils internes",
      "Dashboards",
      "Marketplaces simples",
      "Outils assistés par IA",
      "Panneaux d'administration",
      "Plateformes d'automatisation",
      "Outils de productivité",
      "Portails clients",
      "Plateformes de formation",
    ],
    heroCard: {
      type: "info",
      title: "CE QUE C'EST",
      description:
        "Développement de bout en bout de la première version de votre application web — clarification produit, architecture, frontend, backend, déploiement et passation, livré par un seul développeur full-stack qui peut aussi vous aider à prendre des décisions produit.",
      whenTitle: "QUAND L'UTILISER",
      whenItems: [
        "Vous avez une idée de produit claire et devez livrer la première version",
        "Vous ne pouvez pas ou n'avez pas encore besoin d'une équipe complète",
        "Vous voulez réflexion produit et exécution par la même personne",
        "Vous voulez lancer vite sans accumuler de dette technique",
      ],
      leaveWithItems: [
        "Une application web fonctionnelle en production",
        "Un périmètre produit clarifié en cours de route",
        "Un code livré avec documentation",
        "Des fondations prêtes pour la phase suivante",
      ],
    },
    painPoints: [
      "Vous avez une idée de produit claire mais pas d'équipe technique pour la construire.",
      "Vous ne pouvez pas financer une équipe de développement à temps plein pour un produit non validé.",
      "Vous ne savez pas comment cadrer, architecturer et livrer une première version réaliste.",
      "Vous avez besoin de quelqu'un capable à la fois de réfléchir au produit et de le construire.",
      "Vous voulez lancer vite sans construire une dette technique que vous regretterez.",
    ],
    outcomes: [
      "Application web fonctionnelle livrée",
      "Clarification produit incluse",
      "Déploiement complet géré",
      "Passation de code avec documentation",
    ],
    included: [
      { title: "Clarification produit", description: "Sessions de découverte pour s'aligner sur le périmètre, les priorités et les critères de succès." },
      { title: "Architecture technique", description: "Conception système, modèles de données, contrats API et plan d'infrastructure." },
      { title: "Frontend", description: "UI React ou Next.js construite selon votre structure produit et votre direction design." },
      { title: "Backend", description: "API Node.js avec Express, authentification, logique métier et intégrations." },
      { title: "Base de données", description: "Conception de schéma PostgreSQL ou Supabase, migrations et optimisation de requêtes." },
      { title: "Déploiement et passation", description: "Déploiement en production sur Cloudflare Pages, Vercel ou votre hébergeur préféré, plus documentation complète du code." },
    ],
    pricing: [{ label: "Développement MVP sur mesure", price: "dès 4 500 EUR", featured: true }],
    pricingNote:
      "Fourchette typique : 6 000 EUR – 15 000 EUR selon le périmètre. Devis sur mesure fourni après un appel de découverte.",
    goodFit: [
      "Vous avez un problème clair à résoudre",
      "Vous pouvez prioriser et réduire le périmètre",
      "Vous avez un budget réaliste",
      "Vous voulez une première version propre et déployable",
      "Vous êtes ouvert à une approche MVP par étapes",
    ],
    notAFit: [
      "Vous voulez une marketplace ou un réseau social complexe en deux semaines",
      "Vous n'avez aucun budget ou refusez de discuter du périmètre",
      "Vous attendez des fonctionnalités illimitées à prix fixe",
      "Vous cherchez des arrangements uniquement en equity",
    ],
    processSteps: [
      { title: "Découverte", description: "Je cartographie avec vous l'idée produit, les utilisateurs cibles, les fonctionnalités indispensables, les contraintes et les risques." },
      { title: "Périmètre et proposition", description: "Je rédige un document de périmètre clair avec jalons, calendrier et proposition à prix fixe." },
      { title: "Sprint de construction", description: "Le développement se déroule en sprints ciblés avec points d'étape et mises à jour régulières." },
      { title: "Revue", description: "Vous testez le produit fonctionnel et donnez votre retour avant la livraison finale." },
      { title: "Déploiement et passation", description: "Le produit est déployé en production et transmis avec une documentation complète." },
    ],
    faqs: [
      { question: "Combien coûte un MVP ?", answer: "Le développement MVP démarre à 4 500 EUR. La plupart des projets se situent entre 6 000 EUR et 15 000 EUR selon le périmètre." },
      { question: "Combien de temps cela prend-il ?", answer: "Cela dépend du périmètre. Un petit MVP peut prendre quelques semaines. Un MVP plus complexe nécessite une feuille de route par étapes." },
      { question: "Pouvez-vous aider à définir le périmètre d'abord ?", answer: "Oui. L'Atelier AI Clarity Bootstrap est recommandé avant le développement si l'idée n'est pas encore claire." },
      { question: "Pouvez-vous inclure des fonctionnalités IA ?", answer: "Oui, si elles sont utiles et réalistes pour la première version." },
      { question: "Gérez-vous le déploiement ?", answer: "Oui. Le déploiement et la passation sont inclus." },
      { question: "Pouvez-vous travailler avec du code existant ?", answer: "Oui, après revue. Les projets existants peuvent nécessiter un audit d'abord." },
      { question: "Fournissez-vous du design ?", answer: "Je peux créer des structures UI produit propres, mais une identité de marque avancée ou sur mesure peut nécessiter un designer dédié." },
      { question: "Que se passe-t-il après le lancement ?", answer: "Vous pouvez réserver des journées de développement, du support, des améliorations ou un nouveau sprint." },
    ],
  },
};
