import type { LegalPageContent } from './legalNotice';

export const privacyPolicy: Record<'en' | 'fr' | 'es', LegalPageContent> = {
  en: {
    title: 'Privacy policy',
    description: 'How fullstackchris.dev collects, uses, and protects personal data — including newsletter, contact form, and payment information.',
    lastUpdated: '2026-06-13',
    bodyHtml: `
      <p>
        This privacy policy explains what personal data is collected through
        <a href="https://fullstackchris.dev">fullstackchris.dev</a>, why it is
        collected, who processes it, and the rights you have over your data. It
        is written to be clear and practical rather than exhaustive — if anything
        is unclear, please email
        <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.
      </p>

      <h2>Who is responsible</h2>
      <p>
        Christophe Crognier (auto-entrepreneur, SIREN 851 494 641) is the data
        controller for personal data collected through the Website.
      </p>

      <h2>What data may be collected</h2>
      <ul>
        <li><strong>Email address</strong> — when you subscribe to the AI Clarity Newsletter, send a contact request, or purchase a service.</li>
        <li><strong>Name and company</strong> — if provided through contact or booking forms.</li>
        <li><strong>Postal address and phone number</strong> — only if required for a paid service, invoice, or customer record.</li>
        <li><strong>Message content</strong> — anything you write in a contact form or email.</li>
        <li><strong>Payment metadata</strong> — handled by Stripe (last four digits, country, transaction ID). Full card details are never received or stored by the Website.</li>
        <li><strong>Analytics data</strong> — aggregated, anonymous usage data from Cloudflare Web Analytics (no cookies, no personal identifiers).</li>
        <li><strong>Technical logs</strong> — standard request logs (IP, user agent, timestamp) generated by hosting and security providers for diagnostics and abuse prevention.</li>
      </ul>

      <h2>Why data is collected</h2>
      <ul>
        <li>To respond to contact and quote requests.</li>
        <li>To manage newsletter subscriptions and send issues.</li>
        <li>To deliver and follow up on coaching, development, and workshop services.</li>
        <li>To process payments and issue invoices where required.</li>
        <li>To improve the Website and the relevance of its content.</li>
        <li>To prevent abuse, fraud, and unauthorized access.</li>
      </ul>
      <p>
        The legal bases are: performance of a contract (services and payments),
        consent (newsletter), and legitimate interest (security, analytics,
        improving the Website).
      </p>

      <h2>Third-party processors</h2>
      <p>Some data is processed by trusted third parties acting on behalf of the publisher:</p>
      <ul>
        <li><strong>beehiiv</strong> — newsletter delivery and subscriber management.</li>
        <li><strong>Stripe</strong> — payment processing for services and digital products.</li>
        <li><strong>Cloudflare Web Analytics</strong> — privacy-friendly, cookieless analytics.</li>
        <li><strong>GitHub Pages</strong> — current Website hosting.</li>
        <li><strong>Cloudflare</strong> — DNS, security, and future hosting.</li>
      </ul>
      <p>
        No third-party tracking pixels (Google Analytics, Meta Pixel, LinkedIn
        Insight, advertising remarketing) are used at this time. Tally or
        Formspree are not currently in use; they would be listed here if enabled.
      </p>

      <h2>International transfers</h2>
      <p>
        Some processors (notably Stripe, beehiiv, GitHub, Cloudflare) may process
        data outside the European Economic Area. They rely on appropriate
        safeguards such as Standard Contractual Clauses and equivalent
        certifications under EU–US Data Privacy Framework rules where applicable.
      </p>

      <h2>Data retention</h2>
      <p>Personal data is kept only for as long as necessary for the purposes described in this Privacy Policy.</p>
      <p>Invoices, payment records and accounting documents may be kept for 10 years from the end of the relevant financial year to comply with French accounting obligations.</p>
      <p>Contact requests and business inquiries may be kept for up to 3 years after the last meaningful contact, unless a longer retention period is required to manage a contract, legal obligation or dispute.</p>
      <p>Newsletter subscription data is kept until the subscriber unsubscribes or requests deletion. Pending or unconfirmed newsletter subscribers may be reviewed or deleted periodically.</p>
      <p>Project and client data is kept for the duration of the business relationship, then archived only as long as necessary for contractual, legal, accounting or dispute-related purposes.</p>
      <p>Analytics data is retained according to the analytics provider's settings, minimized and anonymized where possible.</p>

      <h2>Your rights</h2>
      <p>Under the GDPR and applicable French law, you may request:</p>
      <ul>
        <li>Access to your personal data.</li>
        <li>Correction of inaccurate or incomplete data.</li>
        <li>Deletion ("right to be forgotten") within legal limits.</li>
        <li>Objection to processing based on legitimate interest.</li>
        <li>Portability of data you have provided.</li>
        <li>Withdrawal of consent at any time (for newsletter and other consent-based processing).</li>
        <li>Unsubscription from the newsletter — every issue includes a one-click unsubscribe link.</li>
      </ul>
      <p>
        To exercise any of these rights, write to
        <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.
        You also have the right to lodge a complaint with the CNIL
        (<a href="https://www.cnil.fr" target="_blank" rel="noopener noreferrer">cnil.fr</a>),
        the French data protection authority.
      </p>

      <h2>Security</h2>
      <p>
        Reasonable technical and organizational measures are in place to protect
        personal data — including HTTPS, scoped access, modern hosting providers,
        and minimization of stored data. No system is perfectly secure; should an
        incident affect you, you will be informed as required by law.
      </p>

      <h2>Updates to this policy</h2>
      <p>This policy may be updated to reflect changes to the services, providers, or applicable law. Significant changes will be flagged on the Website.</p>

      <h2>Contact</h2>
      <p>Questions or requests about your personal data: <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.</p>
    `,
  },
  fr: {
    title: 'Politique de confidentialité',
    description: "Comment fullstackchris.dev collecte, utilise et protège les données personnelles — y compris newsletter, formulaire de contact et informations de paiement.",
    lastUpdated: '2026-06-13',
    bodyHtml: `
      <p>
        Cette politique de confidentialité explique quelles données personnelles sont collectées via
        <a href="https://fullstackchris.dev">fullstackchris.dev</a>, pourquoi elles sont
        collectées, qui les traite, et les droits dont vous disposez sur vos données. Elle
        est rédigée pour être claire et pratique plutôt qu'exhaustive — si quelque chose
        n'est pas clair, merci d'écrire à
        <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.
      </p>

      <h2>Qui est responsable</h2>
      <p>
        Christophe Crognier (auto-entrepreneur, SIREN 851 494 641) est le responsable
        du traitement des données personnelles collectées via le Site.
      </p>

      <h2>Quelles données peuvent être collectées</h2>
      <ul>
        <li><strong>Adresse e-mail</strong> — lorsque vous vous abonnez à la newsletter AI Clarity, envoyez une demande de contact, ou achetez un service.</li>
        <li><strong>Nom et société</strong> — si fournis via les formulaires de contact ou de réservation.</li>
        <li><strong>Adresse postale et numéro de téléphone</strong> — uniquement si nécessaire pour un service payant, une facture, ou un dossier client.</li>
        <li><strong>Contenu des messages</strong> — tout ce que vous écrivez dans un formulaire de contact ou un e-mail.</li>
        <li><strong>Métadonnées de paiement</strong> — gérées par Stripe (quatre derniers chiffres, pays, ID de transaction). Les détails complets de carte ne sont jamais reçus ni stockés par le Site.</li>
        <li><strong>Données analytiques</strong> — données d'usage agrégées et anonymes issues de Cloudflare Web Analytics (sans cookies, sans identifiants personnels).</li>
        <li><strong>Journaux techniques</strong> — journaux de requêtes standards (IP, user agent, horodatage) générés par les hébergeurs et prestataires de sécurité à des fins de diagnostic et de prévention des abus.</li>
      </ul>

      <h2>Pourquoi les données sont collectées</h2>
      <ul>
        <li>Pour répondre aux demandes de contact et de devis.</li>
        <li>Pour gérer les abonnements à la newsletter et envoyer les numéros.</li>
        <li>Pour livrer et assurer le suivi des services de coaching, développement et ateliers.</li>
        <li>Pour traiter les paiements et émettre des factures lorsque nécessaire.</li>
        <li>Pour améliorer le Site et la pertinence de son contenu.</li>
        <li>Pour prévenir les abus, la fraude et les accès non autorisés.</li>
      </ul>
      <p>
        Les bases légales sont : l'exécution d'un contrat (services et paiements),
        le consentement (newsletter), et l'intérêt légitime (sécurité, analytique,
        amélioration du Site).
      </p>

      <h2>Sous-traitants tiers</h2>
      <p>Certaines données sont traitées par des tiers de confiance agissant pour le compte de l'éditeur :</p>
      <ul>
        <li><strong>beehiiv</strong> — envoi de la newsletter et gestion des abonnés.</li>
        <li><strong>Stripe</strong> — traitement des paiements pour les services et produits numériques.</li>
        <li><strong>Cloudflare Web Analytics</strong> — analytique respectueuse de la vie privée, sans cookies.</li>
        <li><strong>GitHub Pages</strong> — hébergement actuel du Site.</li>
        <li><strong>Cloudflare</strong> — DNS, sécurité, et hébergement futur.</li>
      </ul>
      <p>
        Aucun pixel de suivi tiers (Google Analytics, Meta Pixel, LinkedIn
        Insight, remarketing publicitaire) n'est utilisé actuellement. Tally ou
        Formspree ne sont pas utilisés actuellement ; ils seraient listés ici s'ils étaient activés.
      </p>

      <h2>Transferts internationaux</h2>
      <p>
        Certains sous-traitants (notamment Stripe, beehiiv, GitHub, Cloudflare) peuvent traiter
        des données en dehors de l'Espace économique européen. Ils s'appuient sur des garanties
        appropriées telles que les clauses contractuelles types et des certifications
        équivalentes selon les règles du cadre de protection des données UE–États-Unis lorsque applicable.
      </p>

      <h2>Conservation des données</h2>
      <p>Les données personnelles sont conservées seulement le temps nécessaire aux finalités décrites dans cette politique de confidentialité.</p>
      <p>Les factures, relevés de paiement et documents comptables peuvent être conservés 10 ans à compter de la fin de l'exercice comptable concerné, pour respecter les obligations comptables françaises.</p>
      <p>Les demandes de contact et sollicitations commerciales peuvent être conservées jusqu'à 3 ans après le dernier contact significatif, sauf si une durée de conservation plus longue est requise pour la gestion d'un contrat, d'une obligation légale ou d'un litige.</p>
      <p>Les données d'abonnement à la newsletter sont conservées jusqu'à ce que l'abonné se désinscrive ou demande leur suppression. Les abonnés en attente ou non confirmés peuvent être examinés ou supprimés périodiquement.</p>
      <p>Les données de projet et client sont conservées pendant la durée de la relation commerciale, puis archivées seulement le temps nécessaire à des fins contractuelles, légales, comptables ou liées à un litige.</p>
      <p>Les données analytiques sont conservées selon les paramètres du prestataire d'analytique, minimisées et anonymisées lorsque possible.</p>

      <h2>Vos droits</h2>
      <p>En vertu du RGPD et du droit français applicable, vous pouvez demander :</p>
      <ul>
        <li>L'accès à vos données personnelles.</li>
        <li>La correction de données inexactes ou incomplètes.</li>
        <li>La suppression (« droit à l'oubli ») dans les limites légales.</li>
        <li>L'opposition au traitement fondé sur l'intérêt légitime.</li>
        <li>La portabilité des données que vous avez fournies.</li>
        <li>Le retrait du consentement à tout moment (pour la newsletter et autres traitements basés sur le consentement).</li>
        <li>La désinscription de la newsletter — chaque numéro inclut un lien de désinscription en un clic.</li>
      </ul>
      <p>
        Pour exercer l'un de ces droits, écrivez à
        <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.
        Vous avez également le droit de déposer une plainte auprès de la CNIL
        (<a href="https://www.cnil.fr" target="_blank" rel="noopener noreferrer">cnil.fr</a>),
        l'autorité française de protection des données.
      </p>

      <h2>Sécurité</h2>
      <p>
        Des mesures techniques et organisationnelles raisonnables sont en place pour protéger
        les données personnelles — y compris HTTPS, accès restreint, hébergeurs modernes,
        et minimisation des données stockées. Aucun système n'est parfaitement sécurisé ; en cas
        d'incident vous concernant, vous serez informé conformément à la loi.
      </p>

      <h2>Mises à jour de cette politique</h2>
      <p>Cette politique peut être mise à jour pour refléter des changements de services, de prestataires, ou de la loi applicable. Les changements significatifs seront signalés sur le Site.</p>

      <h2>Contact</h2>
      <p>Questions ou demandes concernant vos données personnelles : <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.</p>
    `,
  },
  es: {
    title: 'Política de privacidad',
    description: 'Cómo fullstackchris.dev recopila, usa y protege los datos personales — incluyendo newsletter, formulario de contacto e información de pago.',
    lastUpdated: '2026-06-13',
    bodyHtml: `
      <p>
        Esta política de privacidad explica qué datos personales se recopilan a través de
        <a href="https://fullstackchris.dev">fullstackchris.dev</a>, por qué se
        recopilan, quién los procesa, y los derechos que tienes sobre tus datos. Está
        escrita para ser clara y práctica en lugar de exhaustiva — si algo no
        está claro, escribe a
        <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.
      </p>

      <h2>Quién es responsable</h2>
      <p>
        Christophe Crognier (auto-entrepreneur, SIREN 851 494 641) es el responsable
        del tratamiento de los datos personales recopilados a través del Sitio.
      </p>

      <h2>Qué datos pueden recopilarse</h2>
      <ul>
        <li><strong>Correo electrónico</strong> — cuando te suscribes a la AI Clarity Newsletter, envías una solicitud de contacto, o compras un servicio.</li>
        <li><strong>Nombre y empresa</strong> — si se proporcionan a través de formularios de contacto o reserva.</li>
        <li><strong>Dirección postal y número de teléfono</strong> — solo si es necesario para un servicio de pago, factura, o registro de cliente.</li>
        <li><strong>Contenido de mensajes</strong> — cualquier cosa que escribas en un formulario de contacto o correo electrónico.</li>
        <li><strong>Metadatos de pago</strong> — gestionados por Stripe (últimos cuatro dígitos, país, ID de transacción). El Sitio nunca recibe ni almacena los datos completos de la tarjeta.</li>
        <li><strong>Datos analíticos</strong> — datos de uso agregados y anónimos de Cloudflare Web Analytics (sin cookies, sin identificadores personales).</li>
        <li><strong>Registros técnicos</strong> — registros de solicitud estándar (IP, user agent, marca de tiempo) generados por los proveedores de hosting y seguridad para diagnóstico y prevención de abusos.</li>
      </ul>

      <h2>Por qué se recopilan los datos</h2>
      <ul>
        <li>Para responder a solicitudes de contacto y presupuesto.</li>
        <li>Para gestionar suscripciones a la newsletter y enviar los números.</li>
        <li>Para entregar y dar seguimiento a servicios de coaching, desarrollo y talleres.</li>
        <li>Para procesar pagos y emitir facturas cuando sea necesario.</li>
        <li>Para mejorar el Sitio y la relevancia de su contenido.</li>
        <li>Para prevenir abusos, fraude y accesos no autorizados.</li>
      </ul>
      <p>
        Las bases legales son: ejecución de un contrato (servicios y pagos),
        consentimiento (newsletter), e interés legítimo (seguridad, analítica,
        mejora del Sitio).
      </p>

      <h2>Encargados del tratamiento (terceros)</h2>
      <p>Algunos datos son procesados por terceros de confianza que actúan en nombre del editor:</p>
      <ul>
        <li><strong>beehiiv</strong> — envío de la newsletter y gestión de suscriptores.</li>
        <li><strong>Stripe</strong> — procesamiento de pagos para servicios y productos digitales.</li>
        <li><strong>Cloudflare Web Analytics</strong> — analítica respetuosa con la privacidad, sin cookies.</li>
        <li><strong>GitHub Pages</strong> — hosting actual del Sitio.</li>
        <li><strong>Cloudflare</strong> — DNS, seguridad, y futuro hosting.</li>
      </ul>
      <p>
        Actualmente no se usan píxeles de seguimiento de terceros (Google Analytics, Meta Pixel, LinkedIn
        Insight, remarketing publicitario). Tally o
        Formspree no están en uso actualmente; se listarían aquí si se habilitaran.
      </p>

      <h2>Transferencias internacionales</h2>
      <p>
        Algunos encargados (en particular Stripe, beehiiv, GitHub, Cloudflare) pueden procesar
        datos fuera del Espacio Económico Europeo. Se basan en garantías
        apropiadas como las Cláusulas Contractuales Tipo y certificaciones
        equivalentes bajo las normas del Marco de Privacidad de Datos UE-EE.UU. cuando sea aplicable.
      </p>

      <h2>Conservación de datos</h2>
      <p>Los datos personales se conservan solo el tiempo necesario para los fines descritos en esta Política de Privacidad.</p>
      <p>Las facturas, registros de pago y documentos contables pueden conservarse durante 10 años desde el final del ejercicio fiscal correspondiente, para cumplir con las obligaciones contables francesas.</p>
      <p>Las solicitudes de contacto y consultas comerciales pueden conservarse hasta 3 años después del último contacto significativo, salvo que se requiera un período de conservación más largo para gestionar un contrato, obligación legal o disputa.</p>
      <p>Los datos de suscripción a la newsletter se conservan hasta que el suscriptor se dé de baja o solicite su eliminación. Los suscriptores pendientes o no confirmados pueden revisarse o eliminarse periódicamente.</p>
      <p>Los datos de proyecto y cliente se conservan durante la relación comercial, y luego se archivan solo el tiempo necesario para fines contractuales, legales, contables o relacionados con disputas.</p>
      <p>Los datos analíticos se conservan según la configuración del proveedor de analítica, minimizados y anonimizados cuando sea posible.</p>

      <h2>Tus derechos</h2>
      <p>Según el RGPD y la ley francesa aplicable, puedes solicitar:</p>
      <ul>
        <li>Acceso a tus datos personales.</li>
        <li>Corrección de datos inexactos o incompletos.</li>
        <li>Eliminación ("derecho al olvido") dentro de los límites legales.</li>
        <li>Oposición al tratamiento basado en interés legítimo.</li>
        <li>Portabilidad de los datos que has proporcionado.</li>
        <li>Retirada del consentimiento en cualquier momento (para la newsletter y otros tratamientos basados en consentimiento).</li>
        <li>Darte de baja de la newsletter — cada número incluye un enlace de baja con un clic.</li>
      </ul>
      <p>
        Para ejercer cualquiera de estos derechos, escribe a
        <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.
        También tienes derecho a presentar una reclamación ante la CNIL
        (<a href="https://www.cnil.fr" target="_blank" rel="noopener noreferrer">cnil.fr</a>),
        la autoridad francesa de protección de datos.
      </p>

      <h2>Seguridad</h2>
      <p>
        Se aplican medidas técnicas y organizativas razonables para proteger
        los datos personales — incluyendo HTTPS, acceso restringido, proveedores de hosting modernos,
        y minimización de los datos almacenados. Ningún sistema es perfectamente seguro; si un
        incidente te afecta, serás informado según lo exige la ley.
      </p>

      <h2>Actualizaciones de esta política</h2>
      <p>Esta política puede actualizarse para reflejar cambios en los servicios, proveedores, o la ley aplicable. Los cambios significativos se señalarán en el Sitio.</p>

      <h2>Contacto</h2>
      <p>Preguntas o solicitudes sobre tus datos personales: <a href="mailto:christophe.crognier@gmail.com">christophe.crognier@gmail.com</a>.</p>
    `,
  },
};
